"""All Pydantic schemas."""
from app.schemas.farmer import (
    FarmerBase,
    FarmerCreate,
    FarmerUpdate,
    FarmerResponse,
    FarmerListResponse,
    FarmerLocation,
    NearbyFarmersQuery,
    FarmerStatsResponse,
)
from app.schemas.fire_alert import (
    FireAlertBase,
    FireAlertCreate,
    FireAlertUpdate,
    FireAlertResponse,
    FireAlertListResponse,
    FireAlertStatsResponse,
    FireAlertQueryParams,
    AlertResponse,
    WhatsAppAlertMessage,
)
from app.schemas.route import (
    RouteBase,
    RouteCreate,
    RouteUpdate,
    RouteDispatch,
    RouteCompletion,
    RouteResponse,
    RouteListResponse,
    RouteOptimizationRequest,
    RouteOptimizationResponse,
    RouteStatsResponse,
    RouteQueryParams,
    RouteStopCreate,
    RouteStopInDB,
)
from app.schemas.carbon_credit import (
    CarbonCreditBase,
    CarbonCreditCreate,
    CarbonCreditUpdate,
    CarbonCreditResponse,
    CarbonCreditListResponse,
    CarbonCreditCalculation,
    CarbonCreditCalculationResponse,
    CreditVerificationRequest,
    CreditCertificationRequest,
    CreditSaleRequest,
    CreditSaleResponse,
    TransactionResponse,
    CarbonCreditStatsResponse,
    CreditQueryParams,
)

__all__ = [
    # Farmer
    "FarmerBase",
    "FarmerCreate",
    "FarmerUpdate",
    "FarmerResponse",
    "FarmerListResponse",
    "FarmerLocation",
    "NearbyFarmersQuery",
    "FarmerStatsResponse",
    # Fire Alert
    "FireAlertBase",
    "FireAlertCreate",
    "FireAlertUpdate",
    "FireAlertResponse",
    "FireAlertListResponse",
    "FireAlertStatsResponse",
    "FireAlertQueryParams",
    "AlertResponse",
    "WhatsAppAlertMessage",
    # Route
    "RouteBase",
    "RouteCreate",
    "RouteUpdate",
    "RouteDispatch",
    "RouteCompletion",
    "RouteResponse",
    "RouteListResponse",
    "RouteOptimizationRequest",
    "RouteOptimizationResponse",
    "RouteStatsResponse",
    "RouteQueryParams",
    "RouteStopCreate",
    "RouteStopInDB",
    # Carbon Credit
    "CarbonCreditBase",
    "CarbonCreditCreate",
    "CarbonCreditUpdate",
    "CarbonCreditResponse",
    "CarbonCreditListResponse",
    "CarbonCreditCalculation",
    "CarbonCreditCalculationResponse",
    "CreditVerificationRequest",
    "CreditCertificationRequest",
    "CreditSaleRequest",
    "CreditSaleResponse",
    "TransactionResponse",
    "CarbonCreditStatsResponse",
    "CreditQueryParams",
]
